#!/usr/bin/env bash
# Installs and sets up dev environment for ngnix

# apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
  	listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
	server_name _;
        rewrite ^/redirect_me(.*)$ http://www.youtube.com/ permanent;
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;}
        rewrite ^/redirect_me(.*)$ http://www.youtube.com permanent;

        location / {
                try_files $uri $uri/ =404;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]
then
    service nginx restart
else
    service nginx start
fi
