#!/usr/bin/env bash
# Installs and sets up dev environment for ngnix with 301 redirect

apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me(.*)$ http:\/\/www.youtube.com permanent$1;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;}/g" /etc/nginx/sites-available/default
/etc/init.d/nginx restart
